### ISSUE TITLE
Fix Brian's project line

### ISSUE THREAD

**Issue by thierrychau** [DPI-WE/first-project#41]

**Comment by brendareyes-techprep** [comment]
Not quite sure how to do this. Can we schedule a time to chat?

**Comment by thierrychau** [comment]
Sure I would love to walk you through this fix. Schedule some time on my calendly

**Comment by thatcantbeso** [comment]
Hey guys, I think we may have to move this to the next quarter. We have other important projects to finish.

**Comment by brendareyes-techprep** [comment]
Done! THANKS THIERRY
